### ISSUE TITLE
Argparser not found

### ISSUE THREAD

**Issue by Rishi-V** [Kei18/lacam#13]
I am following your readme instructions, and after I recursive clone and run ```cmake -B build && make -C build``` I encounter:
```In file included from .../lacam/main.cpp:1:0:
.../lacam/third_party/argparse/include/argparse/argparse.hpp:33:15: fatal error: any: No such file or directory
compilation terminated.
CMakeFiles/main.dir/build.make:75: recipe for target 'CMakeFiles/main.dir/main.cpp.o' failed```

Running on with Ubuntu 16.04 and have cmake version 3.27.5.

**Comment by Kei18** [comment]
I think you missed git submodules when you cloned this repo. Could you try initializing git submodules or retry cloning with the following?

```sh
git clone --recursive https://github.com/Kei18/lacam.git
```

Kei

**Comment by Rishi-V** [comment]
I have verified that I have recursively cloned the submodules correctly. I see the third_party folder populated with argparse and googletest. I still encounter the same issue.

**Comment by Kei18** [comment]
This is very strange... I just confirmed that the compilation was successful for both MacOS and Ubuntu 20.04 (w/Cmake 3.27.2), as well as Github actions hosted on ubuntu-latest.
https://github.com/Kei18/lacam/actions/runs/6372976295/job/17296307511

So I guess this is not a problem for this repo. Could you provide more details, such as OS/cmake info, so that I can help?

---
edited: Sorry, I missed the info at the top

**Comment by Rishi-V** [comment]
Update: I am able to get it working on a Ubuntu 20 machine with cmake version 3.16.3. I think it is safe to say it is an issue with Argparse in Ubuntu 16 and unrelated to your repo. I'll look into it separately, thanks!
